class Ek_Lobe play abstract{
    virtual
    void Think(){}

    virtual
    void Tick(){}
}

class Ek_SensorLobe:Ek_Lobe abstract{
    virtual
    Ek_Stimulus Sense(Ek_Actor This, Ek_Stimulus Stim=null)
    {return null;}
}

class Ek_PlannerLobe:Ek_Lobe abstract{
    virtual
    Name Plan(Ek_Stimulus Stim)
    {return '';}
}

class Ek_ActuatorLobe:Ek_Lobe abstract{
    virtual
    bool Act(Ek_Actor This, Name PlanOAction)
    {return false;}
}